### ISSUE TITLE
Incorrectly blocked domain - `blocklist.site`

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#1]
Your blocklist blocks `blocklist.site`, which is a safe domain that hosts antimalware lists for `The Blocklist Project` (not affiliation).
This is due to the filter blocking all `.site` domains. Even with strict blocking disabled, it breaks the website
https://www.virustotal.com/gui/url/c60e81d4c68ee96a9eae5d37ea4226dd46e82eafb022631d8a2e42770151a6ec/detection

**Comment by VernonStow** [comment]
Thank you, @iam-py-test

**Comment by iam-py-test** [comment]
@VernonStow Thanks for fixing this so quickly

**Comment by iam-py-test** [comment]
One question: How did you find the domains in this list? Just curious.

**Comment by VernonStow** [comment]
Some of the domains were listed in an article about a malware campaign, and others I observed while analyzing Twitter spam and phishing campaigns.

**Comment by iam-py-test** [comment]
@VernonStow Do you accept domain submissions?
If so, should I open another issue or just make a pull request?

**Comment by VernonStow** [comment]
@iam-py-test I welcome domain submissions. Opening another issue would be fine, thanks.

**Comment by iam-py-test** [comment]
@VernonStow posted.
Sorry I did not see your response earlier; I was busy.

**Comment by iam-py-test** [comment]
@VernonStow uBlock Origin shows it is invalid even thought it still works. I can switch it to `||site^$domain=~balabolka.site|~blocklist.site` in my fork or you can make the change later

![image](https://user-images.githubusercontent.com/84232764/120566272-e65ce080-c3dc-11eb-8704-a1bc550237d1.png)

**Comment by VernonStow** [comment]
I fixed it, thanks. I wondered why it was showing in red even though the filter appeared to work properly.

**Comment by iam-py-test** [comment]
@VernonStow maybe it is a uBlock Origin bug.
I can report it to uBlockOrigin/uBlock-Issues if you think it is

**Comment by VernonStow** [comment]
Probably more of a quirk than a bug. It should require the pipe to separate domains: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#domain
