### ISSUE TITLE
False positive - good.third-party.site

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#10]
`good.third-party.site` is blocked as it is a .site domain.
This site should be owned by DuckDuckGo, and seems safe.
Link to reproduce: http://privacy-test-pages.glitch.me/privacy-protections/https-upgrades/
VT: https://www.virustotal.com/gui/url/55bdfc14dd4c6616ae70a4e150a5fc1cbad03f5e4c27362e95baeea22aa43dd4/detection

**Comment by VernonStow** [comment]
Thanks. Fixed in https://github.com/VernonStow/Filterlist/commit/95fb9106447e8ee1fd979157b52ddc248b0c8dc8
