### ISSUE TITLE
False positive - pof[.]com

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#11]
Based on my research, `pof[.]com` is not a tracking server but an dating website.
It might be better to just block subdomains like `ads[.]pof[.]com` rather then the entire domain.
According to my research, there are many scammers on this service, but apart from that, I can not comment on the security/privacy of it as I never have used it

**Comment by VernonStow** [comment]
Thanks for the info. URL Void says it's non-malicious, so I'll delete it. https://www.urlvoid.com/scan/pof.com/

**Comment by iam-py-test** [comment]
Thank you
