### ISSUE TITLE
False positive - kali[.]download

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#12]
This website seems to be the official download website of Kali Linux, which is a Linux distro for ethical hackers
It is detected by one AV on VT but the website where this link was on seems safe and official
The download is too large to upload to VT but I feel it probably is clean

**Comment by VernonStow** [comment]
URL Void and Scumware.org show it as hosting some malicious downloads, so I think it's best to leave it blocked to protect casual users. People who know about and want to download Kali Linux will know how to unblock it ;-)

**Comment by iam-py-test** [comment]
Hmm...
https://www.virustotal.com/gui/file/797ea573ff5676a193666e5e8e04cff23b8abda9d7e3edf2e2fec141e9be222f?nocache=1
https://www.virustotal.com/gui/file/64f3f07d72c95e3e31a053eb90c91f04a94277ca67273521e4220d9068a9857f?nocache=1
Weird???
I did download Kali Linux and it's running fine, but who knows
