### ISSUE TITLE
Unblock safe .ml domains

### ISSUE THREAD

**Issue by bbhtt** [VernonStow/Filterlist#14]
https://github.com/VernonStow/Filterlist/blob/7a55ca89c7f2e1b33942f94be0f27897ee23e203/Filterlist.txt#L16 blocks some safe .ml domains used by FOSS projects

The one's that I come across are:

1. lemmy.ml https://join-lemmy.org/instances
2. beatbump.ml https://github.com/snuffyDev/Beatbump
3. lingva.ml https://github.com/thedaviddelta/lingva-translate#instances

DandelionSprout has a list https://github.com/DandelionSprout/adfilt/blob/dcb3b704f1f4ff814929753c292670559295963a/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L16

Maybe this can be extended to other TLDs as well.

**Comment by VernonStow** [comment]
Thanks for the info. Surbl no longer lists .ml in the top-20 abused TLDs, so I'll just delete it.

**Comment by VernonStow** [comment]
"Click" and "Link" are now in Surbl's Top 40 abused TLDs, but I hesitate to include them yet due to possible FPs.
