### ISSUE TITLE
False positive: hammertime.cyou

### ISSUE THREAD

**Issue by Antsy4904** [VernonStow/Filterlist#15]
This is a legit website: https://hammertime.cyou/ It is used by discord users to generate timestamps.
Please exclude it.

**Comment by VernonStow** [comment]
Thanks. Fixed in https://github.com/VernonStow/Filterlist/commit/9f7b1937fdb537599354ba135601e183f3f0b426
URL Void: https://www.urlvoid.com/scan/hammertime.cyou/ (safe)
