### ISSUE TITLE
Domain report

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#2]
As per your comment
@iam-py-test I welcome domain submissions. Opening another issue would be fine, thanks.

_Originally posted by @VernonStow in https://github.com/VernonStow/Filterlist/issues/1#issuecomment-853387676_

I would like the report the following domains:
These domains are from https://github.com/DandelionSprout/adfilt/issues/188
```
gogle.net
quatrefeuillepolonaise.xyz
extragifis.site
captcharesolving-universe.com
captcharesolver.com
cpmstatsart.com
instantfwding.com
gamesex.fun
goldprize.xyz
kmip.net
iuqerfsodp9ifjaposdfjhgosurijfaewrwergwff.com
```
I created a fork and can pull request if your ok with it
https://github.com/Random-Security-Tech-For-Users/Filterlist/blob/master/Filterlist.txt

**Comment by VernonStow** [comment]
All added, thanks. Feel free to pull request.
