### ISSUE TITLE
Incorrect blocking - checkout.square.site

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#6]
checkout.square.site is a site which appears to be used for money transfers.
Blocking this breaks  https://www.exploringoverland.com/tipjar, which is benign. 
https://www.virustotal.com/gui/url/7ad6ef80c75f654356da7245939359784fac6232d81a4974c37e285e563cf8b7/detection shows no av detections, so it seems safe.

**Comment by VernonStow** [comment]
Fixed, thanks!
