### ISSUE TITLE
PUP-related domain - `planduringe[.]fun`

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#7]
### What is the domain you are reporting?
`planduringe.fun`
### Why are you reporting it?

This domain was (accidently) reported to Easylist in https://forums.lanik.us/viewtopic.php?f=62&t=45626&p=158349, but (due to lack of information) it was never investigated. 
According to McAfee and Webroot, this domain hosts PUPs.
See https://www.virustotal.com/gui/url/0a07c1dc78b52ec190f2c09bc23c6ae2d1efdbd23c04100850c3bede5ebf7beb/detection and https://www.siteadvisor.com/sitereport.html?url=planduringe.fun.
Also, [Norton lists it as _Caution_](https://safeweb.norton.com/report/show?url=planduringe.fun) and alphaMountain.ai marks it as _Suspicious_.

**Comment by VernonStow** [comment]
It appeared to be non-dangerous per URL Void and Zscaler, but in any case it's already covered by the existing TLD filter blocking the .fun domain.

**Comment by iam-py-test** [comment]
Sorry I forgot about the .fun domain block.
Maybe the tld block should be updated to $all to have maximum blocking

**Comment by VernonStow** [comment]
I added $all to the TLDs except for .site, which I might have to remove altogether if a lot of legitimate websites start using it.
