### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#8]
Because there is no License specified, I am curious what license is the project under and is it ok to copy domains from it.
Thanks!

**Comment by VernonStow** [comment]
It's a line item in the list itself, https://opensource.org/licenses/0BSD Zero-Clause BSD

**Comment by iam-py-test** [comment]
> It's a line item in the list itself, https://opensource.org/licenses/0BSD Zero-Clause BSD

Oh. I must have missed that.
Thanks
