### ISSUE TITLE
Malware domain

### ISSUE THREAD

**Issue by iam-py-test** [VernonStow/Filterlist#9]
This is a malware domain. 
### Sources:
https://www.virustotal.com/gui/file/ec95a688a2d4343ae7065f7f47d5abeb6ff1567e782c4304b21949be14d2edfd/relations
https://www.virustotal.com/gui/url/4ed2d7286c664b7e35bcfa94eb9fd3d34dd9d41c2033aa7ce2be1b901b2071c8/detection
https://www.virustotal.com/gui/url/bb3aaf7cc145ac04be0bcfc6032259f7647305e546bad9edacefc0bbbd72b701/detection
### Proposed filter:
```
111bjs.com$all
www.111bjs.com$all
```

**Comment by VernonStow** [comment]
Added, thanks.
